### ISSUE TITLE
Scroll jank on popup

### ISSUE THREAD

**Issue by jonjanisch** [spacejack/mithril-select#1]
On the [demo page ](https://spacejack.github.io/mithril-select/), if you click "Mandarin" and then press the keyboard down arrow multiple times the popup's vertical scroll bar position will shift up or down.

![scroll_issue](https://user-images.githubusercontent.com/668699/44545155-4aa5ce00-a6e2-11e8-937a-36f4cb3b2181.gif)

**Comment by spacejack** [comment]
Thanks, good point. I should be using `preventDefault` on the keyboard events I think.

**Comment by spacejack** [comment]
Hi, I've published an update that should fix that. You can try it [here](https://spacejack.github.io/mithril-select/).

**Comment by jonjanisch** [comment]
Looks good, I'll close this issue.
